### ISSUE TITLE
出现bug了

### ISSUE THREAD

**Issue by yanjuncq** [scola/Qart#2]
FATAL EXCEPTION: main
                                                                    java.lang.IllegalArgumentException: width must be > 0
                                                                        at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:270)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:544)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:514)
                                                                        at com.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:293)
                                                                        at io.github.scola.qart.MainActivity$6.onPreExecute(MainActivity.java:315)
                                                                        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:586)
                                                                        at android.os.AsyncTask.execute(AsyncTask.java:534)
                                                                        at io.github.scola.qart.MainActivity.startConvert(MainActivity.java:296)
                                                                        at io.github.scola.qart.MainActivity.access$400(MainActivity.java:55)
                                                                        at io.github.scola.qart.MainActivity$4.onClick(MainActivity.java:240)
                                                                        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:169)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        at android.os.Looper.loop(Looper.java:153)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5341)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:929)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by scola** [comment]
@yanjuncq Is this always issue and how to reproduce it ?
maybe it's the https://github.com/edmodo/cropper library issue
