### ISSUE TITLE
Qart stops running 

### ISSUE THREAD

**Issue by Hauwertlhaufn** [scola/Qart#3]
For me it stops running after I want to open a picture. I've tried it with many pictures and the galleries  Google Photo and [LeafPic](https://github.com/HoraApps/LeafPic).

**Comment by scola** [comment]
@Hauwertlhaufn how do you test？
Are you install by Google play？
Is there any logs？

**Comment by Hauwertlhaufn** [comment]
I've isntalled it from Google Play.
When I click on the Gallery button, LeafPic opens. But when I now tap any image, Qart stops instantly.

**Comment by scola** [comment]
@Hauwertlhaufn I downloaded LeafPic and test again. It works normally .
You can send feedback when app crash.
I will get logs by Google play console

**Comment by Hauwertlhaufn** [comment]
I've send the log.

**Comment by scola** [comment]
this issue is fixed, please upgrade app on google play to version 1.4

it's grant permission issue 

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://media/external/file/244406 }} to activity {io.github.scola.qart/io.github.scola.qart.MainActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file/244406 from pid=3771, uid=10406 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
at android.app.ActivityThread.-wrap16(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file/244406 from pid=3771, uid=10406 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1620)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
at android.content.ContentResolver.query(ContentResolver.java:491)
at android.content.ContentResolver.query(ContentResolver.java:434)
at io.github.scola.qart.MainActivity.convertOrientation(MainActivity.java:439)
at io.github.scola.qart.MainActivity.onActivityResult(MainActivity.java:335)
at android.app.Activity.dispatchActivityResult(Activity.java:6456)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
